/*
    Contiene las funcinalidades del carrito, muestra que queremos comprar y si lo queremos podemos 
    eliminar productos que no queramos 
 */
package proyecto_sistema_tiendaelect;
import java.io.FileWriter;
import java.io.IOException;
import Clases.*;
import java.io.File;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Carrito extends javax.swing.JFrame {
    
    // accedemos a los metodos de las clases en donde guardamos las variables temporales 
    ProdTemporal prodTm = new ProdTemporal();
    VarTemporales tm = new VarTemporales();
    int index = tm.getIndexUser();
    Usuario arrUsuarioTienda[] = tm.getArrUsuario();
    int saldo = arrUsuarioTienda[index].getSaldo();
    
    int prodContC = prodTm.getProdCont();
    String productosList = "";
    int total = 0;
    int total2 = 0;
    int reciboCont = 1;
    
    int arrPrecios[] = prodTm.getArrPrecios();
    String arrCarrito[] = prodTm.getArrProductos();
    String arrCarTemp[] = new String[100];
    int arrPreciotemp[] = new int[100];
    public Carrito() {
        initComponents();
        
        // ciclo for para mostar el array de productos que queremos comprar 
        for (int i = 0; i < arrCarrito.length; i++) {
            if (arrCarrito[i] != null) {
                // todo se guarda en un string que luego se mostrar en el espacio de texto
                productosList += i+1+".- "+arrCarrito[i];
            }
        }
        
        // ciclo for para calcular el total de los productos que queremos comprar 
        for (int i = 0; i < arrPrecios.length; i++) {
            if(arrPrecios[i] > 0){
                total += arrPrecios[i];
            }
        }
        
        txtTotal.setText("Total: $"+total);
        
        txTCarritoProd.setText(productosList);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txTCarritoProd = new javax.swing.JTextPane();
        btnComprar = new javax.swing.JButton();
        txtProdABorrar = new javax.swing.JTextField();
        btnEliminarProd = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        errSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Carrito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setViewportView(txTCarritoProd);

        btnComprar.setBackground(new java.awt.Color(0, 255, 255));
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnEliminarProd.setText("Eliminar producto");
        btnEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProdActionPerformed(evt);
            }
        });

        txtTotal.setText("Total: $0");

        errSaldo.setText("      ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(txtTotal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnComprar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(errSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtProdABorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarProd)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProdABorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(txtTotal)
                        .addGap(63, 63, 63)
                        .addComponent(btnComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errSaldo)
                        .addGap(60, 60, 60))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu tiend = new Menu();
        tiend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // comprueba si el saldo que tenemos es suficiente
        if (saldo < total) {
            errSaldo.setText("Su saldo es insuficiente");
        }else {
            // si todo esta correcto se hace la compra 
                      
            File recibo;
            FileWriter reciboW;
            try {
                
                recibo = new File("E:\\Bibliotecas\\Documentos\\NetBeansProjects\\Proyecto_Sistema_TiendaElect\\src\\Recibos\\Recibos.txt");
                reciboW = new FileWriter(recibo,true);
                reciboW.write("Cliente: "+arrUsuarioTienda[index].getNombre()+"\n\nProductos: \n\n"+productosList+"\nTotal: $"+total+"\n\n-------------------------------------------------------------------------------\n\n");
                reciboW.close();
                
            } catch (Exception e) {
                System.out.println("Hubo un error al crear el recibo "+e);
            }
            
            errSaldo.setText(" ");
            saldo -= total;
            arrUsuarioTienda[index].setSaldo(saldo);

            arrCarrito = new String[100];
            prodTm.setArrProductos(arrCarrito);
            arrPrecios = new int[100];
            prodTm.setArrPrecios(arrPrecios);
            txTCarritoProd.setText("");
            txtTotal.setText("Total: $0");
            prodContC = 0;
            prodTm.setProdCont(prodContC);
        }
        
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed
        
        // se hace un nuevo array con todos los elementos que no sean null
        
        int index = Integer.parseInt(txtProdABorrar.getText()) -1;
        int cont = 0;
        System.out.println("borrar: "+arrCarrito[index]);
        arrCarrito[index] = null;
        arrPrecios[index] = 0;
        productosList = "";
        prodContC--;
        prodTm.setProdCont(prodContC);
        
        for (int i = 0; i < arrCarrito.length; i++) {
            if(arrCarrito[i] != null){
                arrCarTemp[cont] = arrCarrito[i];                
            }
            if(arrPrecios[i] > 0) {
                arrPreciotemp[cont] = arrPrecios[i];
            }
            if(arrCarrito[i] != null && arrPrecios[i] > 0){
                cont++;
            }
            
        }
        
        prodTm.setArrProductos(arrCarTemp);
        prodTm.setArrPrecios(arrPreciotemp);
        arrCarrito = prodTm.getArrProductos();
        arrPrecios = prodTm.getArrPrecios();
        
        txTCarritoProd.setText("");
        for (int i = 0; i < arrCarrito.length; i++) {
            if (arrCarrito[i] != null) {
                productosList += i+1+".- "+arrCarrito[i];
            }
        }
        
        // se recalcula el total 
        
        for (int i = 0; i < arrPrecios.length; i++) {
            if (arrPrecios[i] > 0) {
                total2 += arrPrecios[i];
            }
        }
        
        System.out.println(total2);
        System.out.println(total);
        total = total2;
        arrCarTemp = new String[100];
        arrPreciotemp = new int[100];
        
        txtTotal.setText("Total: $"+total);
        txTCarritoProd.setText(productosList);
        cont = 0;total2 = 0;
        
    }//GEN-LAST:event_btnEliminarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel errSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txTCarritoProd;
    private javax.swing.JTextField txtProdABorrar;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
