/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_sistema_tiendaelect;

import Clases.*;
public class tienda extends javax.swing.JFrame {
    
    //Declaracion de productos
    
    // ANTES 
    
    /*
            Accesorio teclado = new Accesorio("teclado","Logitech",300,27,"negro");
            Accesorio mouse = new Accesorio("mouse gamer","Razer",250,78,"blanco");

            Componente porceIntel = new Componente("Procesador i9","Intel",5000,20,"DDR4","3.7 Ghz");
            Componente porceAMD = new Componente("Procesador Ryzen 5 3600","AMD",4500,22,"DDR4","3.6 Ghz");
            Componente tarjetaG = new Componente("Tarjeta RTX 3060","Nvidia",8000,22,"8GB DDR6X","60 Hz");
            Componente Ram = new Componente("Memorya Ram","Hyperx",900,22,"8Gb DDR4","3000 Mhz");

            Almacenamiento HDD = new Almacenamiento("Disco duro", "Western Digital",1000,23,1000);
            Almacenamiento SSD = new Almacenamiento("Unidad de estado solido", "Adata",800,23,240);
    */
    
    // Con el cambio 
    Producto teclado = new Accesorio("teclado","Logitech",300,27,"negro");
    Producto mouse = new Accesorio("mouse gamer","Razer",250,78,"blanco");
    
    Producto porceIntel = new Componente("Procesador i9","Intel",5000,20,"DDR4","3.7 Ghz");
    Producto porceAMD = new Componente("Procesador Ryzen 5 3600","AMD",4500,22,"DDR4","3.6 Ghz");
    Producto tarjetaG = new Componente("Tarjeta RTX 3060","Nvidia",8000,22,"8GB DDR6X","60 Hz");
    Producto Ram = new Componente("Memorya Ram","Hyperx",900,22,"8Gb DDR4","3000 Mhz");
   
    Producto HDD = new Almacenamiento("Disco duro", "Western Digital",1000,23,1000);
    Producto SSD = new Almacenamiento("Unidad de estado solido", "Adata",800,23,240);
    
    VarTemporales tm = new VarTemporales();
    ProdTemporal prodTm = new ProdTemporal();
    String tempArr[] = prodTm.getArrProductos();
    Usuario arrUsuarioTienda[] = tm.getArrUsuario();
    int prodCont2 = prodTm.getProdCont();
    int arrPreciotemp[] = prodTm.getArrPrecios();


    public tienda() {
        initComponents();
        int index = tm.getIndexUser();
        labelUserName.setText(arrUsuarioTienda[index].getNombre());
        
        if(prodCont2 == 0) numProd.setText("");
        else numProd.setText(Integer.toString(prodCont2));
        
        
        //Desplegar la informacion en el recuadro
        txtTeclado.setText(teclado.MostrarCarateristicas());txtTeclado.setEditable(false);
        txtMouse.setText(mouse.MostrarCarateristicas());txtMouse.setEditable(false);
        txtProcIntel.setText(porceIntel.MostrarCarateristicas());txtProcIntel.setEditable(false);
        txtProcAMD.setText(porceAMD.MostrarCarateristicas());txtProcAMD.setEditable(false);
        txtTarjetaG.setText(tarjetaG.MostrarCarateristicas());txtTarjetaG.setEditable(false);
        txtRam.setText(Ram.MostrarCarateristicas());txtRam.setEditable(false);
        txtHDD.setText(HDD.MostrarCarateristicas());txtHDD.setEditable(false);
        txtSSD.setText(SSD.MostrarCarateristicas());txtSSD.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCarrto = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        labelUserName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        prodMouse = new javax.swing.JButton();
        prodTarjetaG = new javax.swing.JButton();
        prodRam = new javax.swing.JButton();
        prodProIntel = new javax.swing.JButton();
        prodTeclado = new javax.swing.JButton();
        prodProAMD = new javax.swing.JButton();
        prodHDD = new javax.swing.JButton();
        prodSSD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTeclado = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMouse = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtProcAMD = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtTarjetaG = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtRam = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtProcIntel = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtSSD = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtHDD = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        numProd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        btnCarrto.setText("Carrito");
        btnCarrto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrtoActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        labelUserName.setText("jLabel3");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 640));

        prodMouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mouse.png"))); // NOI18N
        prodMouse.setText("jButton3");
        prodMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodMouseActionPerformed(evt);
            }
        });

        prodTarjetaG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarjeta.png"))); // NOI18N
        prodTarjetaG.setText("jButton3");
        prodTarjetaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodTarjetaGActionPerformed(evt);
            }
        });

        prodRam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ram.png"))); // NOI18N
        prodRam.setText("jButton3");
        prodRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodRamActionPerformed(evt);
            }
        });

        prodProIntel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PIntel.png"))); // NOI18N
        prodProIntel.setText("jButton3");
        prodProIntel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodProIntelActionPerformed(evt);
            }
        });

        prodTeclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teclado.png"))); // NOI18N
        prodTeclado.setText("jButton3");
        prodTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodTecladoActionPerformed(evt);
            }
        });

        prodProAMD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pamd.png"))); // NOI18N
        prodProAMD.setText("jButton3");
        prodProAMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodProAMDActionPerformed(evt);
            }
        });

        prodHDD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HDD.png"))); // NOI18N
        prodHDD.setText("jButton3");
        prodHDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodHDDActionPerformed(evt);
            }
        });

        prodSSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SSD.png"))); // NOI18N
        prodSSD.setText("jButton3");
        prodSSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSSDActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtTeclado);

        jScrollPane4.setViewportView(txtMouse);

        jScrollPane5.setViewportView(txtProcAMD);

        jScrollPane6.setViewportView(txtTarjetaG);

        jScrollPane7.setViewportView(txtRam);

        jScrollPane8.setViewportView(txtProcIntel);

        jScrollPane9.setViewportView(txtSSD);

        jScrollPane10.setViewportView(txtHDD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(prodTeclado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(prodProIntel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(prodHDD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(prodTarjetaG, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodProAMD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(prodMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(prodSSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(prodTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(prodProAMD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(prodProIntel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(prodRam, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prodTarjetaG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(prodSSD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(prodHDD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Tienda");

        numProd.setBackground(new java.awt.Color(255, 0, 51));
        numProd.setFont(new java.awt.Font("BagatrixFont", 1, 18)); // NOI18N
        numProd.setForeground(new java.awt.Color(255, 51, 102));
        numProd.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUserName)
                .addGap(27, 27, 27)
                .addComponent(btnCarrto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCarrto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelUserName)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(512, 512, 512))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarrtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrtoActionPerformed
        Carrito car = new Carrito();
        car.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCarrtoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu tiend = new Menu();
        tiend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void prodTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodTecladoActionPerformed
        
        tempArr[prodCont2] = teclado.getNombre()+"\n"+teclado.getMarca()+"\n"+"$ "+Integer.toString(teclado.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = teclado.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();

//        for (int i = 0; i < arrProductos.length; i++) {
//            if(arrProductos[i] != null){
//                System.out.println(i+"--> "+arrProductos[i]);
//            }
//            
//        }
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodTecladoActionPerformed

    private void prodMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodMouseActionPerformed
        
        // se hace un string con toda la informacin del producto y se almacena en un array 
        tempArr[prodCont2] = mouse.getNombre()+"\n"+mouse.getMarca()+"\n"+"$ "+Integer.toString(mouse.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = mouse.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodMouseActionPerformed

    private void prodProIntelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodProIntelActionPerformed
        tempArr[prodCont2] = porceIntel.getNombre()+"\n"+porceIntel.getMarca()+"\n"+"$ "+Integer.toString(porceIntel.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = porceIntel.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodProIntelActionPerformed

    private void prodProAMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodProAMDActionPerformed
        tempArr[prodCont2] = porceAMD.getNombre()+"\n"+porceAMD.getMarca()+"\n"+"$ "+Integer.toString(porceAMD.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = porceAMD.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodProAMDActionPerformed

    private void prodTarjetaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodTarjetaGActionPerformed
        tempArr[prodCont2] = tarjetaG.getNombre()+"\n"+tarjetaG.getMarca()+"\n"+"$ "+Integer.toString(tarjetaG.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = tarjetaG.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodTarjetaGActionPerformed

    private void prodRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodRamActionPerformed
        tempArr[prodCont2] = Ram.getNombre()+"\n"+Ram.getMarca()+"\n"+"$ "+Integer.toString(Ram.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = Ram.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodRamActionPerformed

    private void prodHDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodHDDActionPerformed
        tempArr[prodCont2] = HDD.getNombre()+"\n"+HDD.getMarca()+"\n"+"$ "+Integer.toString(HDD.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = HDD.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodHDDActionPerformed

    private void prodSSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSSDActionPerformed
        tempArr[prodCont2] = SSD.getNombre()+"\n"+SSD.getMarca()+"\n"+"$ "+Integer.toString(SSD.getPrecio())+"\n\n";
        arrPreciotemp[prodCont2] = SSD.getPrecio();
        
        prodTm.setArrPrecios(arrPreciotemp);
        prodTm.setArrProductos(tempArr);
        
        String arrProductos[] = prodTm.getArrProductos();
        prodCont2++;
        prodTm.setProdCont(prodCont2);
        numProd.setText(Integer.toString(prodCont2));
    }//GEN-LAST:event_prodSSDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrto;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel numProd;
    private javax.swing.JButton prodHDD;
    private javax.swing.JButton prodMouse;
    private javax.swing.JButton prodProAMD;
    private javax.swing.JButton prodProIntel;
    private javax.swing.JButton prodRam;
    private javax.swing.JButton prodSSD;
    private javax.swing.JButton prodTarjetaG;
    private javax.swing.JButton prodTeclado;
    private javax.swing.JTextPane txtHDD;
    private javax.swing.JTextPane txtMouse;
    private javax.swing.JTextPane txtProcAMD;
    private javax.swing.JTextPane txtProcIntel;
    private javax.swing.JTextPane txtRam;
    private javax.swing.JTextPane txtSSD;
    private javax.swing.JTextPane txtTarjetaG;
    private javax.swing.JTextPane txtTeclado;
    // End of variables declaration//GEN-END:variables
}
